/**
 * Session Export Utilities
 * 
 * Functions to export session data to various formats (Markdown, JSON).
 */

import type { SessionTimeline, PlaybackFrame } from '../types/transcript';

/**
 * Converts a session timeline to a clean Markdown summary.
 */
export function sessionToMarkdown(session: SessionTimeline): string {
    const lines: string[] = [];

    // Header
    lines.push(`# Session: ${session.slug}`);
    lines.push(`**Project:** ${session.project}`);
    lines.push(`**Agent:** ${session.agent || 'AI'}`);
    lines.push(`**Date:** ${new Date(session.startedAt).toLocaleString()}`);
    lines.push(`**Frames:** ${session.totalFrames}`);
    lines.push('');
    lines.push('---');
    lines.push('');

    // Frames
    session.frames.forEach((frame, index) => {
        switch (frame.type) {
            case 'user_message':
                lines.push(`### 👤 User`);
                lines.push(frame.userMessage?.text || '');
                lines.push('');
                break;

            case 'claude_thinking':
                // Skip thinking in summary unless requested, or use blockquote
                lines.push(`> **AI Thinking:** ${frame.thinking?.text.substring(0, 300)}${frame.thinking?.text && frame.thinking.text.length > 300 ? '...' : ''}`);
                lines.push('');
                break;

            case 'claude_response':
                lines.push(`### 🤖 ${session.agent === 'claude' ? 'Claude' : 'AI'}`);
                lines.push(frame.claudeResponse?.text || '');
                lines.push('');
                break;

            case 'tool_execution':
                const tool = frame.toolExecution;
                if (!tool) break;

                lines.push(`#### 🛠️ Tool: \`${tool.tool}\``);

                if (tool.fileDiff) {
                    lines.push(`Modified \`${tool.fileDiff.filePath}\`:`);
                    lines.push('```' + tool.fileDiff.language);
                    lines.push(tool.fileDiff.newContent);
                    lines.push('```');
                } else if (tool.output) {
                    lines.push('Output:');
                    lines.push('```');
                    lines.push(tool.output.content.substring(0, 1000) + (tool.output.content.length > 1000 ? '\n...' : ''));
                    lines.push('```');
                }
                lines.push('');
                break;
        }
    });

    lines.push('---');
    lines.push(`*Generated by [Recall](https://github.com/farmanp/recall)*`);

    return lines.join('\n');
}

/**
 * Triggers a file download of the given text
 */
export function downloadFile(filename: string, text: string) {
    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
    element.setAttribute('download', filename);

    element.style.display = 'none';
    document.body.appendChild(element);

    element.click();

    document.body.removeChild(element);
}
